name: API Document Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert YML to HTML
        run: |
          npm install -g @redocly/cli
          npx @redocly/cli build-docs openapi/openapi_latest.yaml -o openapi/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
